[package]
name = "dfu-buddy"
version = "0.1.0-alpha4"
authors = ["Oliver Rockstedt <info@sourcebox.de>"]
license = "MIT"
edition = "2021"
rust-version = "1.72"
description = "DFU flash utility with GUI"
homepage = "https://github.com/sourcebox/dfu-buddy"
repository = "https://github.com/sourcebox/dfu-buddy"

[dependencies]
anyhow = "1.0.79"
dfufile = "0.2.0"
dirs = "5.0.1"
futures = "0.3.30"
log = { version = "0.4.20", features = [
    "max_level_debug",
    "release_max_level_info",
] }
regex = "1.10.2"
rfd = "0.12.1"
rusb = { version = "0.9.3" }
serde = { version = "1.0.195", features = ["derive"] }
simple_logger = { version = "4.3.3" }
egui-modal = "0.3.4"

[dependencies.eframe]
version = "0.26.2"
features = ["persistence"]

[features]
default = ["libusb-vendored"]
libusb-vendored = ["rusb/vendored"]

[profile.release]
lto = true
strip = true

[package.metadata.bundle]
identifier = "de.sourcebox.dfu-buddy"
name = "DFU Buddy"
osx_minimum_system_version = "10.12"
