name: Build Linux

on:
  workflow_dispatch

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-22.04

    env:
      PROJECT_NAME: ${{ github.event.repository.name }}

    steps:
    - uses: actions/checkout@v2

    - name: Install Requirements
      run: |
        export DEBIAN_FRONTED=noninteractive
        sudo apt-get -qq update
        sudo apt-get install -y libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev libxkbcommon-dev
        sudo apt-get install -y libgtk-3-dev
        sudo apt-get install -y patchelf librsvg2-dev

    - name: Install LinuxDeploy
      uses: miurahr/install-linuxdeploy-action@v1
      with:
        plugins: appimage gtk

    - name: Install cargo-deb
      run: cargo install cargo-deb

    - name: Build AppImage
      run: ./build-linux-appimage.sh

    - name: Archive AppImage
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.PROJECT_NAME }}-x86_64.AppImage
        path: target/release/appimage/*.AppImage

    - name: Pack .deb package
      run: cargo deb --no-build

    - name: Archive .deb package
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.PROJECT_NAME }}-x86_64.deb
        path: target/debian/*.deb
